In [ ]:
import numpy as np
import pandas as pd

In [ ]:
file_id = '1K-qffEKS6xNxtK-tM2jjFN9eHVj3H3ho'
url = f'https://drive.google.com/uc?id={file_id}'

In [ ]:
data = pd.read_csv(url)
data.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
data = data.drop('Poster_Link', axis=1)

In [ ]:
data.shape

(1000, 15)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Certificate    899 non-null    object
 3   Runtime        1000 non-null   object
 4   Genre          1000 non-null   object
 5   IMDB_Rating    1000 non-null   float64
 6   Overview       1000 non-null   object
 7   Meta_score     843 non-null    float64
 8   Director       1000 non-null   object
 9   Star1          1000 non-null   object
 10  Star2          1000 non-null   object
 11  Star3          1000 non-null   object
 12  Star4          1000 non-null   object
 13  No_of_Votes    1000 non-null   int64
 14  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(12)
memory usage: 117.3+ KB

In [ ]:
data['Released_Year'] = pd.to_numeric(data['Released_Year'], errors='coerce')

In [ ]:
data['Runtime'] = data['Runtime'].str.strip('min')

In [ ]:
data.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994.0,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,1972.0,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,The Dark Knight,2008.0,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,The Godfather: Part II,1974.0,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,12 Angry Men,1957.0,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
data['Runtime'] = data['Runtime'].astype('float')

In [ ]:
data['Gross'] = data['Gross'].str.replace(',', '').astype(float)

In [ ]:
data.describe()

,Released_Year,Runtime,IMDB_Rating,Meta_score,No_of_Votes,Gross
count,999.000000,1000.000000,1000.000000,843.000000,1.000000e+03,8.310000e+02
mean,1991.217217,122.891000,7.949300,77.971530,2.736929e+05,6.803475e+07
std,23.297025,28.093671,0.275491,12.376099,3.273727e+05,1.097500e+08
min,1920.000000,45.000000,7.600000,28.000000,2.508800e+04,1.305000e+03
25%,1976.000000,103.000000,7.700000,70.000000,5.552625e+04,3.253559e+06
50%,1999.000000,119.000000,7.900000,79.000000,1.385485e+05,2.353089e+07
75%,2009.000000,137.000000,8.100000,87.000000,3.741612e+05,8.075089e+07
max,2020.000000,321.000000,9.300000,100.000000,2.343110e+06,9.366622e+08

In [ ]:
data.describe(include='object')

,Series_Title,Certificate,Genre,Overview,Director,Star1,Star2,Star3,Star4
count,1000,899,1000,1000,1000,1000,1000,1000,1000
unique,999,16,202,1000,548,660,841,891,939
top,Drishyam,U,Drama,A man in London tries to help a counter-espion...,Alfred Hitchcock,Tom Hanks,Emma Watson,Rupert Grint,Michael Caine
freq,2,234,85,1,14,12,7,5,4

In [ ]:
data['Certificate'].unique()

array(['A', 'UA', 'U', 'PG-13', 'R', nan, 'PG', 'G', 'Passed', 'TV-14',
       '16', 'TV-MA', 'Unrated', 'GP', 'Approved', 'TV-PG', 'U/A'],
      dtype=object)

In [ ]:
data.isnull().sum()

Series_Title       0
Released_Year      1
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [ ]:
data.isnull().mean()*100

Series_Title      0.0
Released_Year     0.1
Certificate      10.1
Runtime           0.0
Genre             0.0
IMDB_Rating       0.0
Overview          0.0
Meta_score       15.7
Director          0.0
Star1             0.0
Star2             0.0
Star3             0.0
Star4             0.0
No_of_Votes       0.0
Gross            16.9
dtype: float64

In [ ]:
data['Certificate'] = data['Certificate'].fillna('No Certificate')

In [ ]:
data['Meta_score'] = data['Meta_score'].fillna(data['Meta_score'].median())

In [ ]:
data.dropna(subset= ['Gross', 'Released_Year'], inplace=True)

In [ ]:
data.isnull().sum()

Series_Title     0
Released_Year    0
Certificate      0
Runtime          0
Genre            0
IMDB_Rating      0
Overview         0
Meta_score       0
Director         0
Star1            0
Star2            0
Star3            0
Star4            0
No_of_Votes      0
Gross            0
dtype: int64

**Top 10 Directors by gross**

In [33]:
pd.options.display.float_format = '{:,.0f}'.format
director_gross = data.groupby('Director')['Gross'].sum().sort_values(ascending=False).head(10)
director_gross

Director
Steven Spielberg    2,478,133,165
Anthony Russo       2,205,039,403
Christopher Nolan   1,937,454,106
James Cameron       1,748,236,602
Peter Jackson       1,597,312,443
J.J. Abrams         1,423,170,905
Brad Bird           1,099,627,795
Robert Zemeckis     1,049,446,456
David Yates           978,953,721
Pete Docter           939,382,131
Name: Gross, dtype: float64

**Top 10 Star 1 by Gross**

In [34]:
actor_gross = data.groupby('Star1')['Gross'].sum().sort_values(ascending=False).head(10)
actor_gross

Star1
Tom Hanks           2,319,259,521
Joe Russo           2,205,039,403
Leonardo DiCaprio   1,877,321,752
Daniel Radcliffe    1,835,901,034
Christian Bale      1,351,591,432
Robert Downey Jr.   1,150,720,327
Elijah Wood         1,035,942,020
Daisy Ridley          936,662,225
Mark Hamill           922,340,616
Craig T. Nelson       870,022,836
Name: Gross, dtype: float64

**Top 3 years with the most movies (most active year)**

In [ ]:
data['Released_Year'].value_counts(sort=True).head(3)

Released_Year
2,014    31
2,004    29
2,013    27
Name: count, dtype: int64

**Average Runtime for drama movies (not useful insight but just for code)**

In [ ]:
drama_movies = data[data['Genre'].str.contains('Drama')]
average_runtime = drama_movies['Runtime'].mean()
average_runtime

np.float64(128.53020134228188)

**Average runtime for each decade (Does the runtime of movies changes when time passes?)**

In [ ]:
def extract_decade(x):
    first = int(x // 100)
    last = int((x % 100) // 10) * 10
    if last == 0:
        last = '00'

    return str(first) + str(last)

In [ ]:
data['decade']=data['Released_Year'].apply(extract_decade)

In [ ]:
data['decade'].unique()

array(['1990s', '1970s', '2000s', '1950s', '2010s', '1960s', '1980s',
       '1940s', '1930s', '1920s'], dtype=object)

In [ ]:
Runtime_by_decade = data.groupby('decade')['Runtime'].mean().sort_values(ascending=False)
Runtime_by_decade

decade
1960s   130
2010s   127
1950s   125
2000s   124
1990s   124
1970s   123
1980s   121
1930s   116
1940s   113
1920s    88
Name: Runtime, dtype: float64

We can see thar run time increased when time passed, but does it influence the gross?

In [ ]:
Runtime_by_decade = data.groupby('decade')[['Runtime', 'Gross']].mean().sort_values(by='Gross', ascending=False)
Runtime_by_decade

        Runtime       Gross
decade
2010s       127 103,720,361
2000s       124  69,658,081
1980s       121  62,314,866
1990s       124  61,229,999
1970s       123  52,879,527
1960s       130  31,634,777
1930s       116  18,403,476
1950s       125  14,174,694
1940s       113   8,293,462
1920s        88   1,844,978

In [37]:
Gross_by_decade = data.groupby('decade')['Gross'].mean().sort_values(ascending=False)
Gross_by_decade

decade
2010s   103,720,361
2000s    69,658,081
1980s    62,314,866
1990s    61,229,999
1970s    52,879,527
1960s    31,634,777
1930s    18,403,476
1950s    14,174,694
1940s     8,293,462
1920s     1,844,978
Name: Gross, dtype: float64

**Top Actor by Total Gross**

In [ ]:
actors = pd.concat([
    data[['Star1', 'Gross']].rename(columns={'Star1': 'actor'}),
    data[['Star2', 'Gross']].rename(columns={'Star2': 'actor'}),
    data[['Star3', 'Gross']].rename(columns={'Star3': 'actor'}),
    data[['Star4', 'Gross']].rename(columns={'Star4': 'actor'}),
])

top_actor_gross = actors.groupby('actor')['Gross'].sum().sort_values(ascending=False).head(1)
top_actor_gross

actor
Robert Downey Jr.   3,129,073,242
Name: Gross, dtype: float64

# Task

Complete the analysis with these questions:

*   Top 3 years with the highest gross
*   Most Common Movie Genre
*   Top 5 Directors by Number of Movies

In [ ]:
data.to_csv('movies.csv', index=False)